### PR TITLE
add exopen to fastify organisations

### PR DESCRIPTION
**Pull request by marcus13371337**
## Description
Add exopen to fastify organisations

## Check List

- [X] I have read the [Contributing Guidelines](./CONTRIBUTING.md)

### CODE REVIEW

**Comment by Uzlopak** [comment]
you could reduce the size of the svg online via
https://svgomg.net/

**Comment by marcus13371337** [comment]
@Uzlopak cool, thanks for the site, the file is now optimized!

**Review by Uzlopak — APPROVED** [review]
LGTM

**Comment by Eomm** [comment]
Closing due this org decision: https://github.com/fastify/website/issues/255

**Pull request closed without merging**
