### PR TITLE
Docs: Added Errsole to the organizations

### PR DESCRIPTION
**Pull request by mrrishimeena**
## Description

Added Errsole to the list of organizations.

## Check List

- [x] I have read the [Contributing Guidelines](./CONTRIBUTING.md)

### CODE REVIEW

**Review by gurgunday — APPROVED** [review]

**Comment by mcollina** [comment]
How are you using Fastify exactly?

All your documentation only lists `express`: https://www.errsole.com/documentation/.

**Comment by mrrishimeena** [comment]
> How are you using Fastify exactly?
> 
> All your documentation only lists `express`: https://www.errsole.com/documentation/.

Hi mcollina,

Errsole is a dev-tool product for Node.js developers. The documentation you saw shows how a Node.js developer can use our product in their apps with a basic example using Express.js code. It does not show the tech stack we use for our product. We use Fastify (CJS) in our backend for authentication, authorization, and role assignment for client WebSocket connections.

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
As long as companies continue to promote Express in their main docs and don't add a Fastify option, developers will continue to see Fastify as a second-tier solution.

> We use Fastify (CJS) in our backend for authentication, authorization, and role assignment for client WebSocket connections.

I'm sorry, but I need more clarification because this statement does not add up. Specifically, Errsole claims to be Open Source. Therefore, the implementation at https://github.com/errsole/errsole.js is your product. https://github.com/errsole/errsole.js/blob/2246ba5535424ce59b523837487bb94ba0cce0c4/lib/main/server/index.js#L7 uses Express, and there is no specific Fastify code on your whole GitHub organization (the only examples uses `@fastify/express`).

**Comment by mrrishimeena** [comment]
> As long as companies continue to promote Express in their main docs and don't add a Fastify option, developers will continue to see Fastify as a second-tier solution.
> 
> > We use Fastify (CJS) in our backend for authentication, authorization, and role assignment for client WebSocket connections.
> 
> I'm sorry, but I need more clarification because this statement does not add up. Specifically, Errsole claims to be Open Source. Therefore, the implementation at https://github.com/errsole/errsole.js is your product. https://github.com/errsole/errsole.js/blob/2246ba5535424ce59b523837487bb94ba0cce0c4/lib/main/server/index.js#L7 uses Express, and there is no specific Fastify code on your whole GitHub organization (the only examples uses `@fastify/express`).

Hi mcollina,

Let me clarify a few points about Errsole. We have two versions: errsole-opensource and errsole-cloud. The open-source version offers basic features like viewing, filtering, and searching your app logs with a Built-in dashboard. On the other hand, errsole-cloud includes advanced features to reduce error resolution time from hours to minutes. This includes error context, the HTTP request that caused the error, and online debugger for node.js. The open-source version is just a part of our main product, errsole-cloud (errsole.com).

Now, regarding the use of express.js in our examples and open-source version: Express.js is widely known among Node.js developers, which is why we chose it for our examples and documentation (errsole.com/documentation) as well as for contributors to the open-source project.

As for the comment about 'developers seeing Fastify as a second-tier solution,' I don't believe any framework is second-tier. Developers choose their tech stack based on their specific needs, not based on popularity rankings.

We actually use Fastify in the backend of errsole-cloud (errsole.com), and my PR request is based on this usage, as mentioned on fastify.dev. We use multiple tech stacks based on our requirements and team preferences. If you need more clarification, I am happy to answer it. If any of this contradicts your rules, feel free to close this PR.

**Comment by mcollina** [comment]
I'd need to think about it.

**Pull request closed without merging**
