### PR TITLE
feat: add HEYHEY as an organization

### PR DESCRIPTION
**Pull request by gurgunday**
I'm working on HEYHEY, a platform that proudly went all in on Fastify

### CODE REVIEW

**Review by Eomm — APPROVED** [review]

**Comment by gurgunday** [comment]
Hey @Eomm, quick question

Is there an ETA for when this version of the website would go live? Just excited! 😆

**Comment by Uzlopak** [comment]
Its there?!

image

**Comment by Eomm** [comment]
The website is deployed when the pr is merged

Am I missing something?

**Comment by gurgunday** [comment]
Ah, I got confused because the [deployment](https://6593c895f7667f5cf91db71d--fastify-website-next.netlify.app/) showed it on the homepage too, thanks for pointing out where the organizations are listed, I can confirm that it is indeed there ♥️

Thanks for the replies 🙏

**Comment by Eomm** [comment]
Yeah, the companies in homepage are random at every deploy, meanwhile the company list page lists them all: https://fastify.dev/organisations/

**Pull request merged**
