### PR TITLE
chore(org): add seedium organization to featured list

### PR DESCRIPTION
**Pull request by kostyazgara**
## Description

Add Seedium as an organization to featured list who is actively using Fastify

## Check List

- [x] I have read the [Contributing Guidelines](./CONTRIBUTING.md)

### CODE REVIEW

**Review by gurgunday — COMMENTED** [review]
I think the list is/should be in alphabetical order

**Comment by climba03003** [comment]
Yes, it required to be in alphabetically order.

**Comment by kostyazgara** [comment]
Got it, sorry didn't find that requirement. I will fix that

**Review by climba03003 — APPROVED** [review]

**Review by Fdawgs — APPROVED** [review]

**Comment by Eomm** [comment]
> Yes, it required to be in alphabetically order.

It is no more required: it is sorted automatically:

https://github.com/fastify/website/blob/37c6deaccf70e3ddfa1bca1e6a76db78e8ea05f9/scripts/build-static-data.js#L39

**Pull request merged**
