### PR TITLE
chore: add zero one group into organizations

### PR DESCRIPTION
**Pull request by rubiagatra**
## Description

Adding Zero One Group to the organisations.yml file by request of @Eomm from Twitts...

https://twitter.com/ManuEomm/status/1687709914485956608
Screenshot 2023-08-09 at 15 13 16

## Check List

- [x] I have read the [Contributing Guidelines](./CONTRIBUTING.md)

### CODE REVIEW

**Review by Uzlopak — DISMISSED** [review]
https://zero-one-group.com/technology/

image

Where and how do you use fastify?

**Comment by Uzlopak** [comment]
Oh nevermind. Saw now your tweet.

**Review by mcollina — APPROVED** [review]
lgtm

**Review by Eomm — APPROVED** [review]
🚀

**Pull request merged**
