### PR TITLE
docs: add NTT Com SkyWay to organizations

### PR DESCRIPTION
**Pull request by kadoshita**
## Description

Hello.

I am an employee of a company called NTT Com in Japan.
Our team is developing a CPaaS(Communications Platform as a Service) called SkyWay.
All of SkyWay's server side applications are developed using Fastify.
Fastify's performance and development experience is excellent and we are very grateful to Fastify for supporting our service.
We would be happy to have our brand logo on the Fastify website.

## Check List

- [x] I have read the [Contributing Guidelines](./CONTRIBUTING.md)

### CODE REVIEW

**Comment by Eomm** [comment]
Asking for a friend: Shouldn't this be the added logo?

image

**Comment by kadoshita** [comment]
@Eomm Thank you for your comment.
Sorry for the confusion.

We have company, brand and service logos.
The logo for the SkyWay service is that logo, but it is company policy to use the brand logo.
Therefore, we would like to have the brand's logo on the site.

**Review by Eomm — APPROVED** [review]
image

**Comment by kadoshita** [comment]
Thank you for merging!

**Pull request merged**
