### PR TITLE
fix: only show good first issue labeled issues

### PR DESCRIPTION
**Pull request by Uzlopak**
Currently alot of issues not marked as good first issue are shown. With this change, we filter for 'good first issue' labeled issues

## Check List

- [ ] I have read the [Contributing Guidelines](./CONTRIBUTING.md)

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Review by Eomm — COMMENTED** [review]
> Currently alot of issues not marked as good first issue are shown. With this change, we filter for 'good first issue' labeled issues

Could you share some screen?

I see this (good-first-issue and help wanted):

image

**Comment by Uzlopak** [comment]
This is what I have when starting the PR locally.

image

**Comment by Eomm** [comment]
So we are already showing the `good first issue`s

https://github.com/fastify/fastify/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22

So the change does not modify the output

**Comment by Uzlopak** [comment]
No?

This is what I see on fastify.dev 

image

This is because we are searching "help wanted" and "good first issue" labels.

https://github.com/fastify/gh-issues-finder/blob/920b6b77816ede522b5ed9caa909c9d07337e0db/app.js#L49

So we tainted it with issues, were others just opened an issue with the help template

**Comment by Uzlopak** [comment]
@Eomm 
@mcollina 
Can you please clearify if "first good issues" page should contain "help wanted" labeled issues.

If yes, then close this PR. If no, then this PR should get merged.

**Comment by mcollina** [comment]
Yes, we should include "help wanted" in this list

**Comment by Uzlopak** [comment]
Then it is decided ;)

**Pull request closed without merging**
