### PR TITLE
add gurgunday and uzlopak as collaborators

### PR DESCRIPTION
**Pull request by Uzlopak**
@gurgunday 
is your data correct?

### CODE REVIEW

**Review by gurgunday — APPROVED** [review]
Is the CI failure normal?

Other PRs seem to have failed for the same reason

**Comment by gurgunday** [comment]
It says: `Error: Missing generated file: static/generated/plugins.json. Run the "npm run build:website" once.`

**Comment by Eomm** [comment]
Yes, there is a release with a broken `Ecosystem.md` file format, we need to handle it here:

https://github.com/fastify/website/blob/main/scripts/build-plugin-list.js#L67


```
Error: Invalid entry found in Plugins list (docs/Ecosystem.md): "- throttling the download speed of a request.". This line did not match the expected pattern (/\[`([-a-zA-Z\d./@]+)`\]\(([^)]+)\)(\s*(.+))?/)
    at /home/runner/work/website/website/scripts/build-plugin-list.js:66:13
    at Array.map (<anonymous>)
    at extractPlugins (/home/runner/work/website/website/scripts/build-plugin-list.js:63:31)
    at extractEcosystemFromFile (/home/runner/work/website/website/scripts/build-plugin-list.js:44:18)
    at async generateEcosystemJson (/home/runner/work/website/website/scripts/build-plugin-list.js:26:19)
```

Don't have time before Thursday

**Comment by Uzlopak** [comment]
It is actually taken care of. Problem is, that we have older versions, where the issue still existing. I think that this means, that we have fix ecosystem.md and retag the effected versions/tags

**Comment by Eomm** [comment]
> It is actually taken care of. Problem is, that we have older versions, where the issue still existing. I think that this means, that we have fix ecosystem.md and retag the effected versions/tags

never do that

Let's add some legacy code: https://github.com/fastify/website/pull/153

**Comment by Uzlopak** [comment]
nice.

**Comment by Uzlopak** [comment]
@Eomm 
PTAL

**Review by Eomm — APPROVED** [review]

**Pull request merged**
